# Generated by Django 3.2 on 2021-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseDesc', models.TextField()),
                ('coursePrice', models.CharField(max_length=100)),
                ('courseImage', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
