# Generated by Django 3.2 on 2021-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_courses_courseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseImage',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
